services:
  xray-core:
    build: .
    container_name: xray-core
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      PROXY_TARGET_HOST: 192.168.1.100
    env_file:
      - .env
